# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/01c2d9fb-c7b4-42ad-a0b3-0958d1756f01";
      fsType = "ext4";
    };

  fileSystems."/home/" =
    { device = "/dev/disk/by-uuid/1f38dc37-1661-4160-8ddf-463f9a5df953";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A6CA-8577";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/143a940f-113d-4a0c-b1c1-dc9860d9add7"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  services.thinkfan = {
    enable = true;
    sensors = ''
      hwmon /sys/devices/virtual/thermal/thermal_zone0/temp
      hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
    '';
  };

  # nixpkgs.config.packageOverrides = pkgs: {
  #   vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  # };
  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      pkgsi686Linux.libva

      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      # intel-media-driver # only available starting nixos-19.03 or the current nixos-unstable
    ];
  };
  # hardware.enableAllFirmware = true;
}
