source $HOME/.profile

export KEYTIMEOUT=1 # decrease entering normal mode delay https://www.johnhawthorn.com/2012/09/vi-escape-delays/
bindkey -v

# magic insert
zle -N bracketed-paste
autoload -Uz bracketed-paste-magic url-quote-magic
zle -N bracketed-paste bracketed-paste-magic

# Fix slowness of pastes with zsh-syntax-highlighting.zsh or zsh-autosuggestions.zsh
# https://github.com/zsh-users/zsh-autosuggestions/issues/238#issuecomment-389324292
pasteinit() {
    OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
    zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
    zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish
### Fix slowness of pastes

# history
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.zsh_history
# bindkey '^R' history-incremental-search-backward
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

export ZSH_COMPDUMP=$ZSH/.cache/zcompdump-$HOST
zstyle ':completion:*' menu select
autoload -Uz compinit
compinit

# fzf
if [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
    source /usr/share/doc/fzf/examples/key-bindings.zsh
fi

if [ -d $HOME/.dotfiles/zsh/plugins/zsh-auto-notify ] && [ -x "$(command -v notify-send)" ]; then
    source $HOME/.dotfiles/zsh/plugins/zsh-auto-notify/auto-notify.plugin.zsh
    AUTO_NOTIFY_IGNORE+=("docker" "mpv" "ncmpcpp" "vifm")
fi

if [ -d $HOME/.dotfiles/zsh/plugins/zsh-syntax-highlighting ]; then
    source $HOME/.dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
fi

if [ -d $HOME/.dotfiles/zsh/plugins/zsh-autosuggestions ]; then
    source $HOME/.dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
fi

# if [ -d $HOME/.dotfiles/zsh/plugins/zsh-vi-mode ]; then
#     source $HOME/.dotfiles/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# fi

STARSHIP_INIT="$(starship init zsh --print-full-init 2>/dev/null)"
if [ $? -eq 0 ]; then
    eval $STARSHIP_INIT
fi

# zoxide (must be after prompt-plugin)
ZOXIDE_INIT="$(zoxide init zsh 2>/dev/null)"
if [ $? -eq 0 ]; then
    eval $ZOXIDE_INIT
fi

# export ZSH=$HOME/.dotfiles/ohmyzsh
# plugins=()
# source $ZSH/oh-my-zsh.sh
